version: "3"
services:
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
     - 9090:9090
    volumes:
     - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  garie:
    depends_on:
      - grafana
      - lighthouse
    links:
      - lighthouse  
    image: garie
    environment:
      - LIGHTHOUSE_URL=http://lighthouse:8080
      - PAGE_SPEED_INSIGHTS_KEY
      - LIGHTHOUSE_API_KEY
    ports:
      - 8080:8080
  grafana:
    image: grafana/grafana
    ports:
      - 80:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"  
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
  lighthouse:
    image: lighthouse_ci:latest
    container_name: lighthouse
    ports:
      - "4000:8080"
    cap_add:
      - SYS_ADMIN    